Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('account/',include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sales_basket/', include('sales_basket.urls',namespace= 'sale')),
]

sales_basket/urls.py
from django.urls import path
from . import views


app_name = 'sale'
urlpatterns = [
    path('', views.basket_detail, name='sales_basket'),
    path('add/<int:id>/',views.add_basket, name='add_basket'),
    path('remove/<int:id>/',views.remove_basket,name='remove_basket'),
    path('order/<int:order_id>', views.order, name='order'),
    path('create/',views.order_create, name='order_create'),
    path('request/<int:price>',views.send_request,name='request'),
    path('verify/',views.verify, name='verify'),

]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('contact', views.contact, name='contact'),
    path('product/', views.product, name='product'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('category/<slug>/<int:id>/',views.product, name='category'),
    path('sub_category/<slug>/<int:id>',views.product, name='sub_category'),
    path('like/<int:id>', views.productLike, name='product_like'),
    path('unlike/<int:id>', views.productUnlike, name='product_unlike'),
    path('comment/<int:id>/', views.product_comment, name='product_comment'),
    path('reply/<int:id>/<int:comment_id>',views.comment_reply, name='comment_reply'),
    path('search/', views.product_search, name='product_search')

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from account.models import *
from django.forms import ModelForm
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from django_jalali.db import models as jmodels


class Category(models.Model):
    name = models.CharField(max_length=30,verbose_name='نام' ,unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True,null=True,blank=True)
    created_at = jmodels.jDateTimeField(auto_now_add=True,verbose_name='زمان ایجاد')
    updated_at = jmodels.jDateTimeField(auto_now=True,verbose_name='آخرین تغییر')
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی‌ها'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('category', args=[self.slug,self.id])

class Sub_Category(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='sub',verbose_name='ریز دسته بندی')
    name = models.CharField(max_length=40,unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True,null=True,blank=True)
    created_at = jmodels.jDateTimeField(auto_now_add=True,verbose_name='زمان ایجاد')
    updated_at = jmodels.jDateTimeField(auto_now=True,verbose_name='آخرین تغییر')

    class Meta:
        verbose_name = 'ریز دسته بندی' 
        verbose_name_plural = 'ریز دسته بندی‌ها'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('sub_category', args=[self.slug,self.id])
    
class Product(models.Model):
    VARIANT = (
        ('سایز','سایز'),
        ('رنگ','رنگ'),
    )

    category = models.ManyToManyField(Sub_Category,verbose_name='دسته بندی')
    name = models.CharField(max_length=50,verbose_name='نام')
    amount = models.IntegerField(verbose_name='تعداد')
    price = models.PositiveIntegerField(verbose_name='قیمت')
    discount = models.PositiveIntegerField(verbose_name='تخفیف',blank=True,null=True)
    total_price = models.PositiveIntegerField(verbose_name='قیمت نهایی')
    information = RichTextField(blank=True,null=True,verbose_name='جزئیات محصول')
    image = models.ImageField(upload_to='product/',verbose_name='عکس')
    status = models.CharField(null=True,blank=True,max_length=50,choices=VARIANT)
    available = models.BooleanField(default=True,verbose_name='موجودی')
    created_at = jmodels.jDateTimeField(auto_now_add=True,verbose_name='زمان ایجاد')
    updated_at = jmodels.jDateTimeField(auto_now=True,verbose_name='آخرین تغییر')
    tags = TaggableManager(blank=True)
    like = models.ManyToManyField(User,blank=True,related_name='product_like')
    total_like = models.IntegerField(default=0)
    unlike = models.ManyToManyField(User,blank=True,related_name='product_unlike')
    total_unlike = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return str(self.name)
    
    @property
    def total_price(self):
        if not self.discount: 
            return self.price
        elif self.discount:
            total = (self.discount * self.price) / 100
            return int(self.price - total)
        return self.total_price
    def total_like(self):
        return self.like.count()
    def total_unlike(self):
        return self.unlike.count()
    
    # def available(self):
    #     if self.amount == 0:
    #         return self.available == True
    #     else:
    #         return self.available == False

class Size(models.Model):
    name = models.CharField(max_length=3,verbose_name='سایز')

    class Meta:
        verbose_name = 'سایز'
        verbose_name_plural = 'سایز'
    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=40, verbose_name='نام رنگ')

    class Meta:
        verbose_name = 'رنگ'
        verbose_name_plural = 'رنگ‌ها'
    def __str__(self):
        return self.name

class Variant(models.Model):
    name = models.CharField(max_length=50, verbose_name= 'نام')
    product_variant = models.ForeignKey(Product,on_delete=models.CASCADE, verbose_name= 'محصول')
    size_variant = models.OneToOneField(Size,on_delete=models.CASCADE,null=True,blank=True,verbose_name= 'سایز')
    color_variant = models.ForeignKey(Color,on_delete=models.CASCADE,null=True,blank=True, verbose_name= 'رنگ')
    amount = models.IntegerField(verbose_name= 'تعداد')
    price = models.PositiveIntegerField(verbose_name= 'قیمت')
    discount = models.PositiveIntegerField(blank=True,null=True, verbose_name= 'تخفیف')
    total_price = models.PositiveIntegerField(verbose_name='قیمت نهایی')

    class Meta:
        verbose_name = 'تنوع'
        verbose_name_plural = 'تنوع'

    def __str__(self):
        return self.name
    
    @property
    def total_price(self):
        if not self.discount: 
            return self.price
        elif self.discount:
            total = (self.discount * self.price) / 100
            return int(self.price - total)
        return self.total_price
    
class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.TextField()
    rate = models.PositiveIntegerField(default=1)
    create_at = jmodels.jDateTimeField(auto_now_add=True)
    reply = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='comment_reply')
    is_reply = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'نطر'
        verbose_name_plural = 'نظرها'

    def __str__(self):
        return str(self.product.name)
    
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment','rate']

class ReplyForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment',]

class ImageGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=100,blank=True,null=True)
    image = models.ImageField(upload_to='product/',blank=True,null=True)

    class Meta:
        verbose_name = 'گالری عکس‌ها'
        verbose_name_plural = 'گالری عکس‌ها'
    
    def __str__(self):
        return self.product.name

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=40)

shop/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from sales_basket.models import *
from .models import *
from .forms import *
from django.db.models import Q
from django.views.generic import ListView



class home(ListView):
    model = Sub_Category
    template_name = 'shop/home.html'
    context_object_name = 'sub_category'

@login_required
def contact(request):
    if request.method == 'POST':
        subject = request.POST['subject']
        email = request.POST['email']
        message = request.POST['message']
        body = subject +'\n'+ email+'\n'+message
        form = EmailMessage(
            'contact form',
            body,
            'test',
            ('Alirezaazizishafa0936@gmail.com',)
        )
        form.send(fail_silently=False)
        return render(request, 'shop/contact.html')
    return render(request, 'shop/contact.html')


def product(request,slug=None,id=None):
    product = Product.objects.all()
    category = Category.objects.all()
    form = SearchForm()
    sub_category = Sub_Category.objects.all()
    if slug and id:
        data = get_object_or_404(Sub_Category,slug=slug,id=id)
        product = product.filter(category=data)
    context = {'product':product, 'category':category,'sub_category':sub_category,'form':form}
    return render(request, 'shop/products.html', context )

def detail(request,id):
    product = get_object_or_404(Product,id=id)
    comment_form = CommentForm()
    replyform = ReplyForm()
    sales_basket = SalesForm()
    images = ImageGallery.objects.filter(product_id=id)
    similar = product.tags.similar_objects()[:2]
    comment = Comment.objects.filter(product_id=id,is_reply=False)
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        is_like = True
    is_unlike = False
    if product.unlike.filter(id=request.user.id).exists():
        is_unlike = True
    if product.status != None:
        if request.method == 'POST':
            variant = Variant.objects.filter(product_variant_id=id)
            var_id = request.POST.get('selected')
            variants = Variant.objects.get(id=var_id)
        else:
            variant = Variant.objects.filter(product_variant_id=id)
            variants = Variant.objects.get(id=variant[0].id) 
        context = {'product':product, 'variant':variant,'variants':variants,'is_like':is_like,'is_unlike':is_unlike,'comment_form':comment_form,
                   'comment':comment,'replyform':replyform,'images':images,'similar':similar,'sales_basket':sales_basket}
        return render(request, 'shop/detail.html',context)
    else:
        return render(request, 'shop/detail.html',{'product':product,'is_like':is_like,'is_unlike':is_unlike,'comment_form':comment_form,
                        'comment':comment,'replyform':replyform,'images':images,'similar':similar,'sales_basket':sales_basket})

@login_required
def productLike(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
        is_like = False
    else:
        product.like.add(request.user)
        is_like = True
        messages.success(request, 'نظر شما ثبت شد.','success')
    return redirect(url)

@login_required
def productUnlike(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    is_unlike = False
    if product.unlike.filter(id=request.user.id).exists():
        product.unlike.remove(request.user)
        is_unlike = False
    else:
        product.unlike.add(request.user)
        is_unlike = True
        messages.success(request, 'نظر شما ثبت شد.','success')
    return redirect(url)


@require_http_methods(request_method_list=('GET','POST'))
@login_required
def product_comment(request,id):
    url = request.META.get('HTTP_REFERER')
    comment = CommentForm(request.POST)
    if comment.is_valid():
        data = comment.cleaned_data
        Comment.objects.create(comment=data['comment'],rate=data['rate'],user_id=request.user.id,product_id=id)
    return redirect(url)

@require_http_methods(request_method_list=('GET','POST'))
@login_required
def comment_reply(request,id,comment_id):
    url = request.META.get('HTTP_REFERER')
    replyform = ReplyForm(request.POST)
    if replyform.is_valid():
        data = replyform.cleaned_data
        Comment.objects.create(comment=data['comment'],product_id=id,user_id=request.user.id,reply_id=comment_id,is_reply=True)
        messages.success(request, 'نظر شما ثبت شد!')
        return redirect(url)
    
def product_search(request):
    product = Product.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']
            if data is not None:
                product = product.filter(name__icontains=data)
            return render(request, 'shop/products.html',{'product':product,'form':form})

shop/templates/shop/contact.html
{% extends 'base.html' %}
{% block title %}ارتباط با ما{% endblock %}

{% block body %}
<div class="container">
    <div class="card bg-dark mt-5 p-5">
        <form method="POST">
            {% csrf_token %}
            <h1 class="text-center" style="color: goldenrod;">ارتباط با ما</h1>
            <div class="row mt-3">
                <div class="col-6">
                    <input type="text" name="subject" placeholder="موضوع" class="form-control" required>
                </div>
                <div class="col-6">
                    <input type="email" name="email" placeholder="ایمیل" class="form-control" required>
                </div>
            </div>
            <div class="row mt-3">
                <textarea name="message" rows="5" placeholder="متن" class="form-control" required></textarea>
            </div>
            <button class="btn btn-danger mt-3" type="submit">ارسال</button>
        </form>
    </div>
</div>
{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'shop/detail.css' %}">
<link rel="stylesheet" href="{% static 'shop/comment.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block title %}جزئیات محصول{% endblock %}


{% block body %}

<main class="container">
 
    <!-- Left Column / Headphones Image -->
    <div class="left-column">
      <img data-image="black" src="{{ product.image.url }}" >
    </div>
   
   
    <!-- Right Column -->
    <div class="right-column">
   
      <!------------- Product Description --------------->
      <div class="product-description">
        <span>{{category}}</span>
        <h1>{{product.name}}</h1>
      </div>
      <p>{{ product.information|safe }}</p>
      <div>

        <!---------------- VAriant --------------------->
        {% if product.status == 'سایز' %}
          <form method="POST" style="display: flex;">
            {% csrf_token %}
            <h5 style="margin-left: 10px; margin-top: 10px;">  سایز:</h5>
            <!-- <select style="background-color: darkcyan; border-radius: 10%; border: 1px solid;" name="size" id="size"> -->
            {% for data in variant %}
              <!-- <option value="{{data.id}}" {% if variants.id == data.id %} checked {% endif %} name="selected" onchange="this.form.submit();">{{data.size_variant}}</option> -->
              <input type="radio" value="{{data.id}}" {% if variants.id == data.id %} checked {% endif %} name="selected" onchange="this.form.submit();">
              <a>{{data.size_variant}}</a>
            {% endfor %}
            <!-- </select>             -->
          </form>
        {% endif %}



        <div class="row">
          {% for img in images %}
            <img src="{{img.image.url}}" style="width: 70px; height: 70px;">
          {% endfor %}
        </div>


        <!------------------ Price ---------------------->



      <div class="product-price">
        {% if variants != None %}
          {% if variants.discount %}
          <div>
            <small><s>{{variants.price}}</s></small>
            <span>{{variants.total_price}} تومان</span>
          </div>
          {% else %}
            <span>{{variants.total_price}} تومان</span>
          {% endif %}

        {% else %}
          {% if product.discount %}
          <div>
            <small><s>{{product.price}}</s></small>
            <span>{{product.total_price}} تومان</span>
          </div>
          {% else %}
            <span>{{product.total_price}} تومان</span>
          {% endif %}
        {% endif %}
      </div>


      <!------------------ Sale Form -------------------->


      <div class="card" style="margin-bottom: 20px;">
        {% if product.status != None %}
          <form method="POST" action="{% url 'sale:add_basket' product.id %}">
            {% csrf_token %}
            <input type="hidden" name="selected" value="{{variants.id}}">
            <input type="number" name="quantity" min="1" value="1" max="{{variants.amount}}" required oninvalid="setCustomValidity('تعداد بیشتر از {{product.amount}} در انبار موجود نیست.')">
            {{message}}
            <button class="cart-btn" type="submit" style="font-size: 15px;">سبد خرید <i class="fa fa-shopping-basket" aria-hidden="true"></i>
            </button>
          </form>
        {% else %}
          <form method="POST" action="{% url 'sale:add_basket' product.id %}">
            {% csrf_token %}
            <input type="number" name="quantity" min="1" value="1" max="{{product.amount}}" required oninvalid="setCustomValidity('تعداد بیشتر از {{product.amount}} در انبار موجود نیست.')">
            {{message}}
            <button class="cart-btn" type="submit" style="font-size: 15px;">سبد خرید <i class="fa fa-shopping-basket" aria-hidden="true"></i>
            </button>
          </form>
      </div>

      {% endif %}


      <!------------------------- Like --------------------------->

      <small>{{product.total_like}}</small>
        {% if is_like %}
          <a href="{% url 'product_like' product.id %}" class="btn {% if is_unlike %} disabled {% endif %}" style="border: none;"><i class="fa fa-thumbs-up" style="color: red; font-size:24px"></i></a>
        {% else %}
          <a href="{% url 'product_like' product.id %}" class="btn {% if is_unlike %} disabled {% endif %}" style="border: none;"><i class="fa fa-thumbs-up" style="color: gray; font-size:24px"></i></a>
        {% endif %}

        <small>{{product.total_unlike}}</small>
        {% if is_unlike %}
          <a href="{% url 'product_unlike' product.id %}" class="btn {% if is_like %} disabled {% endif %}" style="border: none;" ><i class="fa fa-thumbs-down" style="color: black; font-size:24px"></i></a>
        {% else %}
          <a href="{% url 'product_unlike' product.id %}" class="btn {% if is_like %} disabled {% endif %}" style="border: none;"><i class="fa fa-thumbs-down" style="color: gray; font-size:24px"></i></a>
        {% endif %}
      </div>
      <!-- Comment Form -->
      {% for comment in comment %}
      {% endfor %}
      <div class="row comment" style="display: block;">
        <div class="col-6">
          <form method="POST" action="{% url 'product_comment' product.id %}">
            {% csrf_token %}
            <div class="card">
              <div class="row">
                <div class="col-12">
                  <div class="comment-box">
                    <h4>Add comment</h4>
                    <div class="rating">
                      <input type="radio" name="rate" value="5" id="5"><label for="5">&star;</label>
                      <input type="radio" name="rate" value="4" id="4"><label for="4">&star;</label>
                      <input type="radio" name="rate" value="3" id="3"><label for="3">&star;</label>
                      <input type="radio" name="rate" value="2" id="2"><label for="2">&star;</label>
                      <input type="radio" name="rate" value="1" id="1"><label for="1">&star;</label>
                    </div>
                    <div class="comment-box">
                      <textarea name="comment" class="form-control" rows="4" required oninvalid="setCustomValidity('!نظری درج نشده است')"></textarea>
                    </div>
                    <div class="text-right me-1">
                      <button type="submit" class="btn btn-danger">ثبت</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form> 
        </div>
      </div>
    <div>
    {% for comment in comment %}
      <div class="card bg-dark text-white">
        <div class="row">
          <div class="col-8">
            <p style="font-weight: 800;">{{comment.user.username}} :</p>
          </div>
          <div class="col-4">
            <div class="comment-rating">
              <i class="fa fa-star {% if coment.rate < 1 %}-o empty {% endif %}"></i>
              <i class="fa fa-star {% if coment.rate < 2 %}-o empty {% endif %}"></i>
              <i class="fa fa-star {% if coment.rate < 3 %}-o empty {% endif %}"></i>
              <i class="fa fa-star {% if coment.rate < 4 %}-o empty {% endif %}"></i>
              <i class="fa fa-star {% if coment.rate < 5 %}-o empty {% endif %}"></i>
            </div>
          </div>
        </div>
        <div class="row">
          <p>{{comment.comment}}</p>
        </div>
        <form method="POST" action="{% url 'comment_reply' product.id comment.id %}">
          {% csrf_token %}
          <textarea name="comment" id="comment" class="form-control" rows="4" placeholder="پاسخ" required oninvalid="setCustomValidity('!نظری درج نشده است')"></textarea>
          <class class="mt-2">
            <button type="submit" class="btn btn-danger">ثبت</button>
          </class>
        </form>
        {% for data in comment.comment_reply.all %}
          <div class="bg-info mt-2 p-2">
            <h6 style="color: black; font-weight: 800;">{{comment.user.username}} :</h6>
            <p>{{data.comment}}</p>
          </div>
        {% endfor%}
      </div>
    {% endfor %}
      
    </div>

  </main>
  <footer>
    <hr>
    <div class="similar">
        {% for tag in similar %}
        <a href="{% url 'detail' tag.id %}">
          <h5>{{tag.name}}</h5>
          <img src="{{ tag.image.url}}" alt="similar-product">
          <small>{{tag.price}}</small>
        </a>
        {% endfor %}
    </div>
  </footer>
{% endblock %}

shop/templates/shop/home.html
{% extends 'base.html' %}


{% block title %}Ecommerce{% endblock %}


{% block body %}
<h1>Home page</h1>

{% for cat in sub_category %}
<a style="text-decoration: none;" href="{{ cat.get_absolute_url }}">
    <h1>{{cat.name}}</h1>
    <!-- <img src="{{ category.image.url }}" alt=""> -->
</a>
{% endfor %}
{% endblock %}

shop/templates/shop/products.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}محصولات{% endblock %}


{% block body %}

<main>
    <div class="container">
        <form method="POST", action="{% url 'product_search' %}">
            {% csrf_token %}
            {{form}}
            <button type="submit">جستوجو</button>
        </form>
        <h1>محصولات</h1>
        {% for product in product %}
        <a style="text-decoration: none;" href="{% url 'detail' product.id %}">
        <h2>{{product.name}}</h2>
        
        {% thumbnail product.image '200x200' as img %}
        <img src="{{ img.url }}" style="width: 200px ;">
        {% endthumbnail %}
        
        {% if product.discount %}
            <small><s>{{product.price}}</s></small>
            <small>{{product.total_price}}</small>
        {% else %}
            <small>{{product.price}}</small>
        {% endif %}
        </a>
        {% endfor %}
    </div>
</main>
{% endblock %}