Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('account/',include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sales_basket/', include('sales_basket.urls',namespace= 'sale')),
]

sales_basket/urls.py
from django.urls import path
from . import views


app_name = 'sale'
urlpatterns = [
    path('', views.basket_detail, name='sales_basket'),
    path('add/<int:id>/',views.add_basket, name='add_basket'),
    path('remove/<int:id>/',views.remove_basket,name='remove_basket'),
    path('order/<int:order_id>', views.order, name='order'),
    path('create/',views.order_create, name='order_create'),
    path('request/<int:price>',views.send_request,name='request'),
    path('verify/',views.verify, name='verify'),

]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('contact', views.contact, name='contact'),
    path('product/', views.product, name='product'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('category/<slug>/<int:id>/',views.product, name='category'),
    path('sub_category/<slug>/<int:id>',views.product, name='sub_category'),
    path('like/<int:id>', views.productLike, name='product_like'),
    path('unlike/<int:id>', views.productUnlike, name='product_unlike'),
    path('comment/<int:id>/', views.product_comment, name='product_comment'),
    path('reply/<int:id>/<int:comment_id>',views.comment_reply, name='comment_reply'),
    path('search/', views.product_search, name='product_search')

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_basket/models.py
from django.db import models
from shop.models import *
from django.forms import ModelForm
from account.models import User
from django_jalali.db import models as jmodels
from django.forms import ModelForm




class Sales(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='محصول')
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر')
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE,null=True,blank=True,verbose_name='تنوع')
    quantity = models.PositiveIntegerField(verbose_name='تعداد',default=1)

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبد خرید'

    def __str__(self):
        return self.user.username

class SalesForm(ModelForm):
    class Meta:
        model = Sales
        fields = ['quantity',]

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر')
    first_name = models.CharField(max_length=200,verbose_name= 'نام گیرنده')
    last_name = models.CharField(max_length=200,verbose_name='نام خانوادگی')
    phone = models.CharField(max_length=11,verbose_name='شماره همراه')
    email = models.EmailField(verbose_name='ایمیل')
    address = models.CharField(max_length=1000,verbose_name='آدرس')
    IP_address = models.PositiveIntegerField(verbose_name='کد پستی')
    paid = models.BooleanField(default=False,verbose_name='پرداخت شد؟')
    created_at = jmodels.jDateTimeField(auto_now_add=True,verbose_name='زمان ایجاد')


    def __str__(self):
        return self.user.username
    
    def get_price(self):
        total = sum(i.price() for i in self.order_item.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total
    

    
class ItemOrder(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,verbose_name='سفارش',related_name='order_item')
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر')
    product = models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='محصول')
    variant = models.ForeignKey(Variant,on_delete=models.CASCADE,verbose_name='تنوع')
    quantity = models.IntegerField(verbose_name='تعداد')

    def __str__(self):
        return self.user.username
    
    def size(self):
        return self.variant.size_variant.name
    

class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ['user','paid','created_at']
    # fields = ['username','phone','email','first_name','last_name','address','IP_address']

sales_basket/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Product
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.conf import settings
import requests
import json


@login_required
def basket_detail(request):
    basket = Sales.objects.filter(user_id=request.user.id)
    form = OrderForm()
    user = request.user
    total = 0
    for p in basket:
        if p.product.status != None:
            total += p.variant.total_price * p.quantity
        else:
            total += p.product.total_price * p.quantity

    context = {'basket':basket,'total':total,'form':form,'user':user}
    return render(request, 'sales_basket/basket_detail.html',context )

@login_required
def add_basket(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    if product.status != None:
        var_id = request.POST.get('selected')
        data = Sales.objects.filter(user_id=request.user.id,variant_id=var_id)
        if data:
            check = True
        else:
            check = False
    else:
        data = Sales.objects.filter(user_id=request.user.id,product_id=id)
        if data:
            check = True
        else:
            check = False
    if request.method == 'POST':
        var_id = request.POST.get('selected')
        form = SalesForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data['quantity']
            if check == True:
                if product != None:
                    basket = Sales.objects.get(user_id=request.user.id,product_id=id,variant_id=var_id)
                    messages.success(request, '!محصول به سبد شما اضافه شد')
                else:
                    basket = Sales.objects.get(user_id=request.user.id,product_id=id)
                    messages.success(request, '!محصول به سبد شما اضافه شد')

                basket.quantity += clean_data
                basket.save()

            else:
                Sales.objects.create(user_id=request.user.id,product_id=id,variant_id=var_id,quantity=clean_data)
                messages.success(request, 'محصول به سبد شما اضافه شد!')
        return redirect(url)
    
def remove_basket(request,id):
    url = request.META.get('HTTP_REFERER')
    Sales.objects.filter(id=id).delete()
    return redirect(url)

def order(request,order_id):
    order = Order.objects.get(id=order_id)
    context = {'order':order}
    return render(request, 'sales_basket/order.html',context)


@require_http_methods(request_method_list=('GET','POST'))
def order_create(request):
    form = OrderForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        order = Order.objects.create(user_id=request.user.id,email=data['email'],first_name=data['first_name']
                            ,last_name=data['last_name'],phone=data['phone'],address=data['address'],IP_address=data['IP_address'])

        basket = Sales.objects.filter(user_id=request.user.id)
        for basket in basket:
            ItemOrder.objects.create(order_id=order.id,user_id=request.user.id,product_id=basket.product_id,
                                     variant_id=basket.variant_id,quantity=basket.quantity)
        return redirect('sale:order',order.id)
    





if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'


ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"


description = "تراکنش شما با موفقیت انجام شد"
CallbackURL = 'http://127.0.0.1:8080/sale:verify/'


def send_request(request,price):
    global amount
    amount = price
    phone = str(request.user.phone)
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": amount,
        "Description": description,
        "Phone": phone,
        "CallbackURL": CallbackURL,
    }
    data = json.dumps(data)
    headers = {'content-type': 'application/json', 'content-length': str(len(data)) }
    try:
        response = requests.post(ZP_API_REQUEST, data=data,headers=headers, timeout=10)

        if response.status_code == 200:
            response = response.json()
            if response['Status'] == 100:
                return {'status': True, 'url': ZP_API_STARTPAY + str(response['Authority']), 'authority': response['Authority']}
            else:
                return {'status': False, 'code': str(response['Status'])}
        return response
    
    except requests.exceptions.Timeout:
        return {'status': False, 'code': 'timeout'}
    except requests.exceptions.ConnectionError:
        return {'status': False, 'code': 'connection error'}


def verify(authority):
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": amount,
        "Authority": authority,
    }
    data = json.dumps(data)
    headers = {'content-type': 'application/json', 'content-length': str(len(data)) }
    response = requests.post(ZP_API_VERIFY, data=data,headers=headers)

    if response.status_code == 200:
        response = response.json()
        if response['Status'] == 100:
            return {'status': True, 'RefID': response['RefID']}
        else:
            return {'status': False, 'code': str(response['Status'])}
    return response

sales_basket/templates/sales_basket/basket_detail.html
{% extends 'base.html' %}

{% block links %}<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">{% endblock %}
{% block title %}سبد خرید{% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <table class="table table-striped table-dark" style="border: 3px solid;">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">عکس</th>
                <th scope="col">محصول</th>
                <th scope="col">سایز</th>
                <th scope="col">رنگ</th>
                <th scope="col">تخفیف</th>
                <th scope="col">قیمت با اعمال تخفیف</th>
                <th scope="col">تعداد</th>
                <th scope="col">قیمت نهایی</th>
                <th scope="col">حذف</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for basket in basket %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td><img src="{{basket.product.image.url}}" style="width: 100px; height: 100px;"></td>
                <td>{{basket.product.name}}</td>
                <td>{{basket.variant.size_variant.name}}</td>
                <td>{{basket.variant.color_variant.name}}</td>
    
                <!-- discount -->
                <td>
                    {% if basket.product.status != None %}
                        {% if basket.variant.discount %}
                            {{basket.variant.discount}}%
                        {% else %}
                            <small>0</small>
                        {% endif %}
                    {% else %}
                        {% if basket.product.discount %}
                            {{basket.product.discount}}%
                        {% else %}
                            <small>0</small>
                        {% endif %}
                    {% endif %}
                </td>
    
                <!-- total discount price -->
                <td>
                    {% if basket.product.status != None %}
                        {{basket.variant.total_price}}
                    {% else %}
                        {{basket.product.total_price}}
                    {% endif %}
                </td>
    
                <td>{{basket.quantity}}</td>
                <!-- total price -->
                <td>
                    {% if basket.product.status != None %}
                        {% widthratio basket.variant.total_price 1 basket.quantity %}
                    {% else %}
                    {% widthratio basket.product.total_price 1 basket.quantity %}
                    {% endif %}
                </td>
    
                <td>
                    <a href="{% url 'sale:remove_basket' basket.id %}"><i class="fa fa-trash"></i></a>
                </td>
              </tr> 
    
            {% endfor %}
            <tr>
                <td style="background-color: #990000;color: white;" colspan="8">جمع کل:</td>
                <td style="background-color: #990000;color: white;" colspan="8">{{total}}</td>
            </tr>
            </tbody>
        </table>
    </div>


    <div class="row">
        <style>
            label{
                margin: 3px 10px;
            }
        </style>
        <form method="POST" action="{% url 'sale:order_create' %}">
            {% csrf_token %}
            <div class="card" style="padding: 15px; margin: 10px; background-color: darkcyan;">
                <label for="first_name">نام گیرنده
                <input type="text" name="first_name" value="{{user.first_name}}" required oninvalid="setCustomValidity('این قسمت را پر کنید')">
                </label>
                <label for="last_name">نام خانوادگی
                <input type="text" name="last_name" value="{{user.last_name}}" required oninvalid="setCustomValidity('این قسمت را پر کنید')">
                </label>
                <label for="phone">شماره همراه
                <input type="number" name="phone" value="{{user.phone}}" required oninvalid="setCustomValidity('این قسمت را پر کنید')">
                </label>
                <label for="email">ایمیل
                <input type="text" name="email" value="{{user.email}}" required oninvalid="setCustomValidity('این قسمت را پر کنید')">
                </label>
                <label for="address">آدرس
                <input type="text" name="address" value="{{user.address}}" required oninvalid="setCustomValidity('این قسمت را پر کنید')">
                </label>
                <label for="IP_address">کد پستی
                <input type="text" name="IP_address" value="{{user.IP_address}}" required oninvalid="setCustomValidity('این قسمت را پر کنید')">
                </label>
            </div>
            <button type="submit" class="btn btn-outline-danger mt-4" ><b>سفارش</b></button>
        </form>
    </div>

</div>

{% endblock %}

sales_basket/templates/sales_basket/order.html
{% extends 'base.html' %}

{% block body %}
<h1>Order</h1>
{% endblock %}